CREATE SEQUENCE BOOK_CATEGORIES_CATEGORY_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE OR REPLACE TRIGGER BOOK_CATEGORIES_CATEGORY_ID_TRG BEFORE
    INSERT ON BOOK_CATEGORIES
    FOR EACH ROW
    WHEN ( new.CATEGORY_ID IS NULL )
BEGIN
    :new.CATEGORY_ID := BOOK_CATEGORIES_CATEGORY_ID_SEQ.nextval;
END;
/
CREATE SEQUENCE BOOK_CATEGORIES_TL_TRANSLATION_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE OR REPLACE TRIGGER BOOK_CATEGORIES_TL_TRANSLATION_ID_TRG BEFORE
    INSERT ON BOOK_CATEGORIES_TL
    FOR EACH ROW
    WHEN ( new.TRANSLATION_ID IS NULL )
BEGIN
    :new.TRANSLATION_ID := BOOK_CATEGORIES_TL_TRANSLATION_ID_SEQ.nextval;
END;
/
CREATE SEQUENCE BOOK_PRICES_BOOK_PRICE_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE OR REPLACE TRIGGER BOOK_PRICES_BOOK_PRICE_ID_TRG BEFORE
    INSERT ON BOOK_PRICES
    FOR EACH ROW
    WHEN ( new.BOOK_PRICE_ID IS NULL )
BEGIN
    :new.BOOK_PRICE_ID := BOOK_PRICES_BOOK_PRICE_ID_SEQ.nextval;
END;
/
CREATE SEQUENCE BOOK_REVIEWS_BOOK_REVIEW_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE OR REPLACE TRIGGER BOOK_REVIEWS_BOOK_REVIEW_ID_TRG BEFORE
    INSERT ON BOOK_REVIEWS
    FOR EACH ROW
    WHEN ( new.BOOK_REVIEW_ID IS NULL )
BEGIN
    :new.BOOK_REVIEW_ID := BOOK_REVIEWS_BOOK_REVIEW_ID_SEQ.nextval;
END;
/
CREATE SEQUENCE BOOKS_BOOK_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE OR REPLACE TRIGGER BOOKS_BOOK_ID_TRG BEFORE
    INSERT ON BOOKS
    FOR EACH ROW
    WHEN ( new.BOOK_ID IS NULL )
BEGIN
    :new.BOOK_ID := BOOKS_BOOK_ID_SEQ.nextval;
END;
/
CREATE SEQUENCE BOOKS_TL_TRANSLATION_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE OR REPLACE TRIGGER BOOKS_TL_TRANSLATION_ID_TRG BEFORE
    INSERT ON BOOKS_TL
    FOR EACH ROW
    WHEN ( new.TRANSLATION_ID IS NULL )
BEGIN
    :new.TRANSLATION_ID := BOOKS_TL_TRANSLATION_ID_SEQ.nextval;
END;
/
CREATE SEQUENCE INVOICE_LINES_INVOICE_LINE_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE OR REPLACE TRIGGER INVOICE_LINES_INVOICE_LINE_ID_TRG BEFORE
    INSERT ON INVOICE_LINES
    FOR EACH ROW
    WHEN ( new.INVOICE_LINE_ID IS NULL )
BEGIN
    :new.INVOICE_LINE_ID := INVOICE_LINES_INVOICE_LINE_ID_SEQ.nextval;
END;
/
CREATE SEQUENCE INVOICES_INVOICE_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE OR REPLACE TRIGGER INVOICES_INVOICE_ID_TRG BEFORE
    INSERT ON INVOICES
    FOR EACH ROW
    WHEN ( new.INVOICE_ID IS NULL )
BEGIN
    :new.INVOICE_ID := INVOICES_INVOICE_ID_SEQ.nextval;
END;
/
CREATE SEQUENCE USERS_USER_ID_SEQ START WITH 1 NOCACHE ORDER;
CREATE OR REPLACE TRIGGER USERS_USER_ID_TRG BEFORE
    INSERT ON USERS
    FOR EACH ROW
    WHEN ( new.USER_ID IS NULL )
BEGIN
    :new.USER_ID := USERS_USER_ID_SEQ.nextval;
END;
/

9 rows selected. 

